In [2]:
import torch

In [3]:
from __future__ import print_function

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.3815, 0.0037, 0.0089],
        [0.0111, 0.3770, 0.1023],
        [0.2506, 0.0970, 0.6530],
        [0.7085, 0.5199, 0.0251],
        [0.2147, 0.1604, 0.3344]])


In [5]:
y = x.view(15)

In [6]:
print(y)

tensor([0.3815, 0.0037, 0.0089, 0.0111, 0.3770, 0.1023, 0.2506, 0.0970, 0.6530,
        0.7085, 0.5199, 0.0251, 0.2147, 0.1604, 0.3344])


In [7]:
z = x.view(-1,15)
print(z)

tensor([[0.3815, 0.0037, 0.0089, 0.0111, 0.3770, 0.1023, 0.2506, 0.0970, 0.6530,
         0.7085, 0.5199, 0.0251, 0.2147, 0.1604, 0.3344]])


In [8]:
x= torch.randn(1)
print(x)
print(x.item())

tensor([-0.7558])
-0.755754292011261


In [9]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [10]:
import numpy

In [11]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [12]:
a.add_(12)

tensor([13., 13., 13., 13., 13.])

In [13]:
b

array([13., 13., 13., 13., 13.], dtype=float32)

False
