In [1]:
import torch
import numpy

In [2]:
x = torch.ones(3,3,requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [3]:
y = x*3

In [4]:
print(y)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<MulBackward0>)


In [6]:
print(y.grad_fn)

In [14]:
z =  y*3
print(z)
while y.data.norm() <10:
    y = y+2
    
print(y)

tensor([[105., 105., 105.],
        [105., 105., 105.],
        [105., 105., 105.]], grad_fn=<MulBackward0>)
tensor([[35., 35., 35.],
        [35., 35., 35.],
        [35., 35., 35.]], grad_fn=<AddBackward0>)


In [10]:
print(x.grad)

None


In [15]:
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([3]) and output[0] has a shape of torch.Size([3, 3]).